# -*- coding: utf-8 -*-
"""factorial_program.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ph4IH4nmXm6X0sElk9JE_WQ3NSsa_l_O
"""

#Calculate factorial of a number
num = int(input("Enter number: "))
factorial = 1
if(num<0):
  print("Negative number!")
elif(num==0):
  print("Factorial of 0 is 1")
else:
  for i in range(1, num+1):
    factorial*=i
    i = i+1
  print(f"Factorial of {num} is:",factorial)

